### ISSUE TITLE
TP crashes on VS 2019 RTM

### ISSUE THREAD

**Issue by xperiandri** [Liminiens/tp-info#1]
``` C#
System.AggregateException: One or more errors occurred. 
---> 
System.NullReferenceException: Object reference not set to an instance of an object.   at TPQuickInfo.QuickInfo.TypeProviderQuickInfoSource.<GetQuickInfoItemAsync>d__4.MoveNext() in C:\Users\hapin\Documents\Programming\tp-info\src\TPQuickInfo\QuickInfo\TypeProviderQuickInfoSource.cs:line 38 
--- End of stack trace from previous location where exception was thrown ---    
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()   
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---    
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)    
--- End of inner exception stack trace ---    
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<UpdateAsync>d__32.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---    
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoPresentationSession.<UpdateAsync>d__5.MoveNext() 
---> 
(Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.   at TPQuickInfo.QuickInfo.TypeProviderQuickInfoSource.<GetQuickInfoItemAsync>d__4.MoveNext() in C:\Users\hapin\Documents\Programming\tp-info\src\TPQuickInfo\QuickInfo\TypeProviderQuickInfoSource.cs:line 38 
--- End of stack trace from previous location where exception was thrown ---    
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()   
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---    
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
<---
```

**Comment by Liminiens** [comment]
Hi! Could you provide a repro? I tested the 1.5 version on VS 2019 16.0 and it seems to work ok :/

**Comment by xperiandri** [comment]
I've cloned your sources.
They didn't build.
I updated all the packages I could.
I built a VSIX in debug and installed it into my VS 2019 RTM instance.
I will play with a project where the exception has occurred and let you know the results. Maybe just packages update will help.

**Comment by xperiandri** [comment]
```
System.AggregateException: One or more errors occurred.
---> System.NullReferenceException: Object reference not set to an instance of an object.
at TPQuickInfo.QuickInfo.TypeProviderQuickInfoSource.<GetQuickInfoItemAsync>d__4.MoveNext()
in C:\Users\hapin\Documents\Programming\tp-info\src\TPQuickInfo\QuickInfo\TypeProviderQuickInfoSource.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of inner exception stack trace ---
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<UpdateAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoPresentationSession.<UpdateAsync>d__5.MoveNext()
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
at TPQuickInfo.QuickInfo.TypeProviderQuickInfoSource.<GetQuickInfoItemAsync>d__4.MoveNext()
in C:\Users\hapin\Documents\Programming\tp-info\src\TPQuickInfo\QuickInfo\TypeProviderQuickInfoSource.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---
```

Visual Studio 2019 16.5.0 Preview 5.0
